version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/app
    restart: always
    command: bash -c "npm set-script prepare '' && npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/app/dist/
      - ./package.json:/usr/app/package.json
    ports:
      - "3333:3333"
      - "9222:9222"
    links:
      - mongo